In [1]:
import numpy as np
P=np.array([[1, 7], [2, 1], [3, 2]])
Q1=np.array([[1, 1], [1, -1]])
print("P:\n",P)
print("Q1:\n",Q1)

P:
 [[1 7]
 [2 1]
 [3 2]]
Q1:
 [[ 1  1]
 [ 1 -1]]


In [ ]:
# Will throw error because matrices have different dimensions
np.add(P,Q1)

In [5]:
Q=np.array([[1, 1], [1, -1], [1,0]])
C1 = np.add(P,Q) # similarly np.subtract
print(f"C1:\n{C1}")

C1:
[[2 8]
 [3 0]
 [4 2]]


In [6]:
P=np.array([[1, 7], [2, 1], [3, 2]])
R=np.array([[1,3,1], [1,0,1]])
print("P*R (P->3x2, R->2x3, hence P*R->3x3):\n",np.dot(P,R))

P*R (P->3x2, R->2x3, hence P*R->3x3):
 [[8 3 8]
 [3 6 3]
 [5 9 5]]


In [7]:
C = np.dot(P,R)
# Calculate determinant of C
det= np.linalg.det(C)
print("np.linalg.det(C): ",det)
print("If det=0, then it is 'Singular Matrix' for which inverse does not exist!")
print("Hence, np.linalg.inv(C): ERROR!")
print(np.linalg.inv(C))

np.linalg.det(C):  0.0
If det=0, then it is 'Singular Matrix' for which inverse does not exist!
Hence, np.linalg.inv(C): ERROR!


LinAlgError: Singular matrix

In [8]:
M=np.array([[1,-1], [2,3]])
print("M:\n",M)
print("np.linalg.det(M): ",np.linalg.det(M))
print("np.linalg.inv(M):\n",np.linalg.inv(M))

M:
 [[ 1 -1]
 [ 2  3]]
np.linalg.det(M):  5.000000000000001
np.linalg.inv(M):
 [[ 0.6  0.2]
 [-0.4  0.2]]


In [24]:
# Taken from Ryan & Matt data science youtube channel
#    https://www.youtube.com/@RyanAndMattDataScience
A = np.array([[1,7], [2,1]])
print(f"Determinant Properties of A:")
print("Det(kA)=k**dim(A)\n")
print("A:\n", A)
print("Det(A):",np.linalg.det(A))
print("\n(kA) where k=3:\n", 3*A)
print("Det(kA)=(k^dim(A)*Det(A):", np.linalg.det(3*A))

Determinant Properties of A:
Det(kA)=k**dim(A)

A:
 [[1 7]
 [2 1]]
Det(A): -13.0

(kA) where k=3:
 [[ 3 21]
 [ 6  3]]
Det(kA)=(k^dim(A)*Det(A): -117.00000000000003


In [2]:
print("Det(AB) = Det(A)*Det(B)")
A = np.array([[2,1],[3,4]])
B = np.array([[0,5],[6,7]])
Det_A = np.linalg.det(A)
Det_B = np.linalg.det(B)
Det_AB = np.linalg.det(np.dot(A,B))
print(f"Det_A:{Det_A}, Det_B:{Det_B}, Det_AB:{Det_AB}")

Det(AB) = Det(A)*Det(B)
Det_A:5.000000000000001, Det_B:-29.99999999999999, Det_AB:-149.99999999999997


In [9]:
print("Det(A) = -Det(A_swapped) --> (where A_swapped refers to swapping of rows or columns)")
print("A:\n", A)
print("Det_A: ", Det_A)
A_swapped_rows = np.array([[3,4],[2,1]])
A_swapped_cols = np.array([[1,2],[4,3]])
print("\nA_swapped_rows:\n", A_swapped_rows)
print("Det_A_swapped_rows:", np.linalg.det(A_swapped_rows))
print("\nA_swapped_cols:\n", A_swapped_cols)
print("Det_A_swapped_cols:", np.linalg.det(A_swapped_cols))

Det(A) = -Det(A_swapped) --> (where A_swapped refers to swapping of rows or columns)
A:
 [[2 1]
 [3 4]]
Det_A:  5.000000000000001

A_swapped_rows:
 [[3 4]
 [2 1]]
Det_A_swapped_rows: -5.000000000000001

A_swapped_cols:
 [[1 2]
 [4 3]]
Det_A_swapped_cols: -4.999999999999999
