In [5]:
import numpy as np

I = np.identity(2) # 2x2 identity matrix
# I = np.eye(2) # this is also the same as above
print(I)

[[1. 0.]
 [0. 1.]]


In [6]:
# Multiplication with identity matrix
A = np.array([[2,5], [6,8]])
prod = np.dot(A, I)
print("np.dot(A,I):\n",prod)

np.dot(A,I):
 [[2. 5.]
 [6. 8.]]


In [8]:
# Inverse of identity matrix = Identity matrix itself
print("np.linalg.inv(I):\n", np.linalg.inv(I))

np.linalg.inv(I):
 [[1. 0.]
 [0. 1.]]


In [9]:
# Eigen values
print("np.linalg.eig(I):\n", np.linalg.eig(I))

np.linalg.eig(I):
 EigResult(eigenvalues=array([1., 1.]), eigenvectors=array([[1., 0.],
       [0., 1.]]))


In [11]:
eigVal, eigVect = np.linalg.eig(I)
print("Eigen values:\n",eigVal)
print("Eigen vectors:\n", eigVect)

Eigen values:
 [1. 1.]
Eigen vectors:
 [[1. 0.]
 [0. 1.]]
