In [1]:
import numpy as np
A = np.array([[7,4], [5,7]])

print("If det(A) != 0, then inverse exists")
print("A:\n", A)
print("det(A):", np.linalg.det(A))
inv_A = np.linalg.inv(A)
print("\nHence inv(A):\n", inv_A)

If det(A) != 0, then inverse exists
A:
 [[7 4]
 [5 7]]
det(A): 28.99999999999999

Hence inv(A):
 [[ 0.24137931 -0.13793103]
 [-0.17241379  0.24137931]]


In [2]:
# Matrix properties
#  1. inv(A).A = A.inv(A) = I
print("Property 1: inv(A).A = A.inv(A) = I\n")
print(f"np.dot(inv_A, A):\n{np.dot(inv_A, A)} \nnp.dot(A, inv_A):\n{np.dot(A, inv_A)}")
print("\nNOTE! We see that there is a slight difference but they are essentially the same!")

Property 1: inv(A).A = A.inv(A) = I

np.dot(inv_A, A):
[[ 1.00000000e+00 -1.11022302e-16]
 [ 2.22044605e-16  1.00000000e+00]] 
np.dot(A, inv_A):
[[1. 0.]
 [0. 1.]]

NOTE! We see that there is a slight difference but they are essentially the same!


In [3]:
# Matrix properties
#  2. inv(AB) = inv(B).inv(A)
print("Property 2: inv(AB) = inv(B).inv(A)")
A = np.array([[2, 1], [5, 3]])
B = np.array([[1, 2], [3, 4]])
print("A:\n", A, "\nB:\n", B)
print("inv(AB):\n", np.linalg.inv(np.dot(A, B)))
print("inv(B).inv(A):\n", np.dot(np.linalg.inv(B), np.linalg.inv(A)))

Property 2: inv(AB) = inv(B).inv(A)
A:
 [[2 1]
 [5 3]] 
B:
 [[1 2]
 [3 4]]
inv(AB):
 [[-11.    4. ]
 [  7.   -2.5]]
inv(B).inv(A):
 [[-11.    4. ]
 [  7.   -2.5]]


In [4]:
# Matrix properties
#  3. transpose(inv(A)) = inv(transpose(A))
print("Property 3: transpose(inv(A)) = inv(transpose(A))")
A_T = A.T #np.transpose(A)
inv_A = np.linalg.inv(A)
print("A:\n", A, "\nA_T:\n", A_T, "\ninv(A):\n", inv_A)
print("\ntranspose(inv(A)):\n", inv_A.T)
print("\n inv(transpose(A))):\n", np.linalg.inv(A_T))

Property 3: transpose(inv(A)) = inv(transpose(A))
A:
 [[2 1]
 [5 3]] 
A_T:
 [[2 5]
 [1 3]] 
inv(A):
 [[ 3. -1.]
 [-5.  2.]]

transpose(inv(A)):
 [[ 3. -5.]
 [-1.  2.]]

 inv(transpose(A))):
 [[ 3. -5.]
 [-1.  2.]]


In [5]:
# Matrix properties
#  4. inv(kA) = 1/k.inv(A)
print("Property 4: inv(kA) = 1/k.inv(A)")
k=2
print("k=",k)
print("inv(kA):\n", np.linalg.inv(k*A))
print("\n(1/k)*inv(A):\n", (1/k)*np.linalg.inv(A))

Property 4: inv(kA) = 1/k.inv(A)
k= 2
inv(kA):
 [[ 1.5 -0.5]
 [-2.5  1. ]]

(1/k)*inv(A):
 [[ 1.5 -0.5]
 [-2.5  1. ]]


In [7]:
# Matrix properties
#   5. inv(inv(A)) = A
print("Property 5: inv(inv(A))=A")
print("A:\n", A)
inv_A = np.linalg.inv(A)
print("inv(A):\n", inv_A)

inv_inv_A = np.linalg.inv(inv_A)
print("inv(inv(A)):\n", inv_inv_A)

Property 5: inv(inv(A))=A
A:
 [[2 1]
 [5 3]]
inv(A):
 [[ 3. -1.]
 [-5.  2.]]
inv(inv(A)):
 [[2. 1.]
 [5. 3.]]
