In [4]:
import numpy as np
A = np.array([[6,4,2], [5,1,3]])
print("A:\n", A)
A_T = A.T # or np.transpose(A)
print("A_T:\n", A_T)

A:
 [[6 4 2]
 [5 1 3]]
A_T:
 [[6 5]
 [4 1]
 [2 3]]


In [7]:
# Properties
#   property 1: Double transpose (A^T)^T = A
print("Property 1: Double transpose (A^T)^T = A")
print("A:\n", A)
A_T = A.T
print("A^T:\n", A_T)
A_T_T = A_T.T
print("\n(A^T)^T:\n", A_T_T)


Property 1: Double transpose (A^T)^T = A
A:
 [[6 4 2]
 [5 1 3]]
A^T:
 [[6 5]
 [4 1]
 [2 3]]

(A^T)^T:
 [[6 4 2]
 [5 1 3]]


In [14]:
# Properties
#   property 2: Transpose of a sum (A+B)^T = A^T + B^T
print("Property 2: Transpose of a sum (A+B)^T = A^T + B^T")
B = np.array([[1,1,4], [3,2,9]])
A_add_B = np.add(A,B)
print("(A_add_B)^T:\n", A_add_B.T)
B_T = B.T
print(f"\nA^T + B^T:\n{np.add(A_T, B_T)}")

Property 2: Transpose of a sum (A+B)^T = A^T + B^T
(A_add_B)^T:
 [[ 7  8]
 [ 5  3]
 [ 6 12]]

A^T + B^T:
[[ 7  8]
 [ 5  3]
 [ 6 12]]


In [20]:
# Properties
#   property 3: Transpose of a product (AB)^T = B^T.A^T
print("property 3: Transpose of a product (AB)^T = B^T.A^T")
A = np.array([[7,2], [5,4], [9,6]])
print(f"A:\n{A} \nB:\n{B}")
AB_T = (np.dot(A,B)).T
print(f"\n(AB)^T:\n{AB_T}")
BtAt = np.dot(B.T,A.T)
print(f"B^T.A^T:\n{BtAt}")

property 3: Transpose of a product (AB)^T = B^T.A^T
A:
[[7 2]
 [5 4]
 [9 6]] 
B:
[[1 1 4]
 [3 2 9]]

(AB)^T:
[[13 17 27]
 [11 13 21]
 [46 56 90]]
B^T.A^T:
[[13 17 27]
 [11 13 21]
 [46 56 90]]


In [28]:
# Properties
#   property 4: Scalar multiplication (kA)^T = k.A^T
print("Property 4: Scalar multiplication (kA)^T = k.A^T")
k = 3
print(f"A:\n{A}")
print(A.shape)
A_T = A.T
print(f"A_T:\n{A_T}")
print(f"\nGiven, k={k}\n")
print(f"(kA)^T:\n{(k*A).T} \nk.A^T:\n{k*A_T}")

Property 4: Scalar multiplication (kA)^T = k.A^T
A:
[[7 2]
 [5 4]
 [9 6]]
(3, 2)
A_T:
[[7 5 9]
 [2 4 6]]

Given, k=3

(kA)^T:
[[21 15 27]
 [ 6 12 18]] 
k.A^T:
[[21 15 27]
 [ 6 12 18]]


In [27]:
# Properties
#   property 5: Transpose inverse inv(C)^T = inv(C^T)
print("Property 5: Transpose inverse inv(C)^T = inv(C^T)")
C = np.array([[2,4,7], [1,5,6], [1,4,8]])
inv_C = np.linalg.inv(C)
print(f"C:\n{C}")
print(f"inv(C)^T:\n{inv_C.T}")
inv_C_T = np.linalg.inv(C.T)
print(f"inv(C^T):\n{inv_C_T}")


Property 5: Transpose inverse inv(C)^T = inv(C^T)
C:
[[2 4 7]
 [1 5 6]
 [1 4 8]]
inv(C)^T:
[[ 0.94117647 -0.11764706 -0.05882353]
 [-0.23529412  0.52941176 -0.23529412]
 [-0.64705882 -0.29411765  0.35294118]]
inv(C^T):
[[ 0.94117647 -0.11764706 -0.05882353]
 [-0.23529412  0.52941176 -0.23529412]
 [-0.64705882 -0.29411765  0.35294118]]
