In [3]:
import numpy as np
from sympy import Matrix

matrix_pre_rref = np.array([
    [2,4,8],
    [1,2,3],
    [4,8,10]
])
rank_matrix_pre_rref = np.linalg.matrix_rank(matrix_pre_rref)
print(f"matrix_pre_rref:\n{matrix_pre_rref}")
print(f"\nRank: {rank_matrix_pre_rref}")

matrix_pre_rref:
[[ 2  4  8]
 [ 1  2  3]
 [ 4  8 10]]

Rank: 2


In [6]:
# Using sympy
sympy_matrix_pre_rref = Matrix(matrix_pre_rref)
matrix_post_rref = sympy_matrix_pre_rref.rref()

print(f"Matrix pre-ref:\n{sympy_matrix_pre_rref}")
print(f"\nMatrix post-ref:\n{matrix_post_rref}")

Matrix pre-ref:
Matrix([[2, 4, 8], [1, 2, 3], [4, 8, 10]])

Matrix post-ref:
(Matrix([
[1, 2, 0],
[0, 0, 1],
[0, 0, 0]]), (0, 2))


In [7]:
# Convert that sympy Matrix in numpy format
np_rref_matrix = np.array(matrix_post_rref[0], dtype=float)
print(f"Convert that sympy Matrix in numpy format:\n{np_rref_matrix}")

Convert that sympy Matrix in numpy format:
[[1. 2. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [9]:
print("Rank of rref:", np.linalg.matrix_rank(np_rref_matrix))

Rank of rref: 2


In [16]:
# Example 2
rref_example_2 = np.array([
    [1,0,0,4],
    [0,1,0,3],
    [0,0,1,8]
])

rank_rref_example_2 = np.linalg.matrix_rank(rref_example_2)
print(f"matrix_pre_rref:\n{rref_example_2}")
print(f"\nRank: {rank_rref_example_2}")
    

matrix_pre_rref:
[[1 0 0 4]
 [0 1 0 3]
 [0 0 1 8]]

Rank: 3


In [15]:
# Example 3
rref_example_3 = np.array([
    [1,0,0,4],
    [0,1,0,3],
    [0,0,1,8],
    [0,0,0,0]
])

rank_rref_example_3 = np.linalg.matrix_rank(rref_example_3)
print(f"matrix_pre_rref:\n{rref_example_3}")
print(f"\nRank: {rank_rref_example_3}")

matrix_pre_rref:
[[1 0 0 4]
 [0 1 0 3]
 [0 0 1 8]
 [0 0 0 0]]

Rank: 3
