In [11]:
import numpy as np
from sympy import Matrix

A = np.array([
    [2,4,3],
    [1,2,3],
    [4,8,10]
])

sympy_mat_pre_rref = Matrix(A)
mat_post_rref = sympy_mat_pre_rref.rref()
print(f"sympy_mat_pre_rref:\n {sympy_mat_pre_rref}")
print(f"mat_post_rref[0]:\n {mat_post_rref[0]}")
print("\nTuple of indices of pivot column mat_post_rref[1]:", mat_post_rref[1])

# converting to numpy array
numpy_rref_matrix = np.array(mat_post_rref[0], dtype=float)
print(f"\nConverting to numpy array:\n{numpy_rref_matrix}")

sympy_mat_pre_rref:
 Matrix([[2, 4, 3], [1, 2, 3], [4, 8, 10]])
mat_post_rref[0]:
 Matrix([[1, 2, 0], [0, 0, 1], [0, 0, 0]])

Tuple of indices of pivot column mat_post_rref[1]: (0, 2)

Converting to numpy array:
[[1. 2. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
