In [1]:
import numpy as np

# CASE 1: Zero Solutions
# x+y+z = 5
# y-3z = 1
# 2x+y+5z = 0
print("CASE 1: Zero Solutions Rank(A)<Rank(A|B)\n")
A = np.array([
    [1,1,1],
    [0,1,-3],
    [2,1,5]
])
print(f"A (which is LHS of eqn):\n{A}")
B = np.array([
    [5], 
    [1],
    [0]
])
print(f"B (which is RHS of eqn):\n{B}")
augmat = np.column_stack((A, B))
print(f"\nAugmenting LHS, RHS, new matrix is:\n{augmat}")

print("\nRank of A  :", np.linalg.matrix_rank(A))
print("Rank of A|B:", np.linalg.matrix_rank(augmat))

print("\nNOTE! np.linalg.solve(A,B) will give an error message because it is a Singular matrix!!!")

CASE 1: Zero Solutions Rank(A)<Rank(A|B)

A (which is LHS of eqn):
[[ 1  1  1]
 [ 0  1 -3]
 [ 2  1  5]]
B (which is RHS of eqn):
[[5]
 [1]
 [0]]

Augmenting LHS, RHS, new matrix is:
[[ 1  1  1  5]
 [ 0  1 -3  1]
 [ 2  1  5  0]]

Rank of A  : 2
Rank of A|B: 3

NOTE! np.linalg.solve(A,B) will give an error message because it is a Singular matrix!!!


In [2]:
# CASE 2: One Solution
# x+2y+3z = 4
# y+4z = 6
# 2z = 2
print("CASE 2: One Solution Rank(A)=Rank(A|B)=n\n")
A = np.array([
    [1,2,3],
    [0,1,4],
    [0,0,2]
])
print(f"A (which is LHS of eqn):\n{A}")
B = np.array([[5],[1],[0]])
print(f"B (which is RHS of eqn):\n{B}")
augmat = np.column_stack((A,B))
print(f"\nAugmenting LHS, RHS, new matrix is:\n{augmat}")
print("\nRank of A  :", np.linalg.matrix_rank(A))
print("Rank of A|B:", np.linalg.matrix_rank(augmat))
print("From the above, we see that Rank(A)=Rank(A|B)=3-->(here n=3, where n is no. of variables)")
print(f"\nHence, solving the eqns, we get:\n{np.linalg.solve(A,B)}")

CASE 2: One Solution Rank(A)=Rank(A|B)=n

A (which is LHS of eqn):
[[1 2 3]
 [0 1 4]
 [0 0 2]]
B (which is RHS of eqn):
[[5]
 [1]
 [0]]

Augmenting LHS, RHS, new matrix is:
[[1 2 3 5]
 [0 1 4 1]
 [0 0 2 0]]

Rank of A  : 3
Rank of A|B: 3
From the above, we see that Rank(A)=Rank(A|B)=3-->(here n=3, where n is no. of variables)

Hence, solving the eqns, we get:
[[3.]
 [1.]
 [0.]]


In [3]:
# CASE 3: Infinite Solutions
# x-y+2z = 4
# 2x-2y+4z = 8
# x+y = 2
print("CASE 3: Infinite Solutions Rank(A)=Rank(A|B) < n\n")
A = np.array([
    [1,-1,2],
    [2,-2,4],
    [1,1,0]
])
print(f"A (which is LHS of eqn):\n{A}")
B = np.array([
    [4],
    [8],
    [2]
])
print(f"B (which is RHS of eqn):\n{B}")
augmat = np.column_stack((A,B))
print(f"\nRank(A)={np.linalg.matrix_rank(A)}, Rank(A|B)={np.linalg.matrix_rank(augmat)}, n=3")

CASE 3: Infinite Solutions Rank(A)=Rank(A|B) < n

A (which is LHS of eqn):
[[ 1 -1  2]
 [ 2 -2  4]
 [ 1  1  0]]
B (which is RHS of eqn):
[[4]
 [8]
 [2]]

Rank(A)=2, Rank(A|B)=2, n=3
