In [4]:
import numpy as np

# Equations
# 2x+2y-z = 8
# 5x+9y+z = 11
# -6x+y-2z = 4

A = np.array([
    [2,2,-1],
    [5,9,1],
    [-6,1,-2]
])

B = np.array([
    [8],
    [11],
    [4]
])
print(f"A:\n{A}")
print(f"B:\n{B}")
aug_A_B = np.column_stack((A,B))
print(f"\naug_A_B:\n{aug_A_B}")

A:
[[ 2  2 -1]
 [ 5  9  1]
 [-6  1 -2]]
B:
[[ 8]
 [11]
 [ 4]]

aug_A_B:
[[ 2  2 -1  8]
 [ 5  9  1 11]
 [-6  1 -2  4]]


In [8]:
# Method to swap rows
print("Swapping row 1 and 2:\n")
print(f"Before swap:\n{aug_A_B}")
aug_A_B[[0,1]] = aug_A_B[[1,0]]
print(f"After swap:\n{aug_A_B}")

Swapping row 1 and 2:

Before swap:
[[ 5  9  1 11]
 [ 2  2 -1  8]
 [-6  1 -2  4]]
After swap:
[[ 2  2 -1  8]
 [ 5  9  1 11]
 [-6  1 -2  4]]


In [9]:
print("Multiply first row by 3")
aug_A_B[0] = 3*aug_A_B[0]
print(f"After multiplication:\n{aug_A_B}")

Multiply first row by 3
After multiplication:
[[ 6  6 -3 24]
 [ 5  9  1 11]
 [-6  1 -2  4]]


In [10]:
print("Add second row to first row and replace in second row\n")
aug_A_B[1] = aug_A_B[0]+aug_A_B[1]
print(f"After addition:\n{aug_A_B}")

Add second row to first row and replace in second row

After addition:
[[ 6  6 -3 24]
 [11 15 -2 35]
 [-6  1 -2  4]]
