In [2]:
import numpy as np

# Example 1: 2x2 matrix
A = np.array([
    [5,3],
    [4,1]
])

eigValues, eigVectors = np.linalg.eig(A)
print(f"Eigen values: {eigValues}")
print(f"\nEigen vectors (Note that these values are normalized vectors):\n{eigVectors}")

Eigen values: [ 7. -1.]

Eigen vectors (Note that these values are normalized vectors):
[[ 0.83205029 -0.4472136 ]
 [ 0.5547002   0.89442719]]


In [5]:
# Example 2: 3x3 matrix
B = np.array([
    [-2,-4,2],
    [-2,1,2],
    [4,2,5]
])

eValues, eVectors = np.linalg.eig(B)
print(f"Eigen Values: {eValues}")
print(f"\nEigen Vectors (Note: these are normalized vectors):\n{eVectors}")

Eigen Values: [-5.  3.  6.]

Eigen Vectors (Note: these are normalized vectors):
[[ 0.81649658  0.53452248  0.05842062]
 [ 0.40824829 -0.80178373  0.35052374]
 [-0.40824829 -0.26726124  0.93472998]]
